SUPABASE_URL = "https://psnzqfhwxguvfvmuzhxh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzbnpxZmh3eGd1dmZ2bXV6aHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA4MTA5NjEsImV4cCI6MjA5NjM4Njk2MX0.poaxMbdNAjNuvMml9lh5GrLz2okQwafRC7zqY-Tru5g"
